apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hava-ing
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: hava.ccie.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hava-svc
            port:
              number: 80
